"""HFN Promote — Generator v3.4. Full article text, anti-spam prompts, feedback-aware generation with per-article learning and A/B testing."""
import json, re, random, uuid, anthropic
import db
from config import ANTHROPIC_API_KEY, GEN_MODEL, MIN_RELEVANCE, HFN_BASE_URL, HFN_CONTENT_DIR

# Only these article parts are allowed on LinkedIn (avoids political content)
LINKEDIN_SAFE_PARTS = {"Jobs & Economy", "Natural Resources"}

def is_linkedin_safe(article):
    """Check if an article's topic is suitable for LinkedIn."""
    return (article.get("part", "") or "") in LINKEDIN_SAFE_PARTS

VOICE = """You are writing social media posts for History Future Now (historyfuturenow.com).

ABOUT THE SITE:
History Future Now puts current events into historical perspective and uses that vantage point to look at the future. It covers four themes: Natural Resources, Global Balance of Power, Jobs & Economy, and Society. Articles are long-form, data-rich essays with interactive charts. The author is Tristan Fischer.

WRITING STYLE — match the History Future Now voice:
- Intellectually confident but accessible. Not academic — conversational authority.
- Uses specific numbers, dates, and historical parallels — "Since 2000, China gained 14 million factory jobs while the US lost 5 million" not "jobs have shifted overseas."
- Connects past patterns to present events: "Every civilisation that ran out of water collapsed. We're next."
- Slightly provocative, never partisan. Challenges assumptions from both left and right.
- Direct, clear sentences. No corporate jargon.
- British English: -ise, -our, -tre, -ence (e.g. "organised", "labour", "centre", "defence").

OPENING LINE:
The first line must make someone stop scrolling. It should feel like something a sharp editor said over drinks — not something generated by a content strategy. No formulas, no templates. Read the article, find the single most interesting thing in it, and lead with that.

GROUNDING RULE:
Every post must contain at least one specific detail that could only come from having read the article — a name, a date, a number, an unexpected historical fact. Generic summaries are worthless. If someone could have written your post without reading the article, it fails.

The chart image IS the visual hook. Do NOT repeat what the chart shows — provoke curiosity that makes the reader study the chart.
- Create a "knowledge gap" — hint at an insight the reader can only get by reading the article.

FORBIDDEN:
- Never say "Here's why", "Let's talk about", "It turns out", "In this article", "Dive into"
- Never use "HFN" — always "History Future Now"
- No hashtags on X. 2-3 hashtags on LinkedIn only (at the very end).
- Never start with "Did you know" or "Have you ever wondered"
- Never be generic. Every post must contain at least one specific number or historical reference.
- NEVER include URLs in the caption. The article URL is appended automatically after generation.
- Never use "But here's the thing" / "And that changes everything" / "This matters because" / "Let that sink in"
- Never use "fascinating" / "crucial" / "remarkable" / "game-changing" / "paradigm"
- Never open with a dramatic short sentence followed by a longer explanatory one (the AI "staccato-explain" pattern)
- Never use sentence fragments for emphasis more than once per post
- Never start consecutive sentences with the same word
- Never use a question as the last line unless it's genuinely interesting (not "What do you think?" or "Agree?")
- No em-dash dramatic pauses more than once per post
- No parallel tricolon form ("X. Y. Z.") unless quoting the source material
- No "In today's world" or "It's important to note"

EXAMPLES OF WHAT TO AVOID vs WHAT TO AIM FOR:

BAD (AI-sounding):
"Rome spent 23% of GDP on defence. Today, Europe is doing the same. And that changes everything. Here's why this matters for the future of democracy."

GOOD (human-quality):
"Germany went from 1% to 23% of GDP on defence in seven years flat. Europe is rearming faster than at any point since the Cold War. History says once the machine starts, it doesn't stop."

BAD (generic, no article detail):
"The history of water tells us something crucial about our future. This remarkable article explores what happens when civilisations run dry."

GOOD (specific, grounded in article):
"The Khmer Empire built 1,000 reservoirs and still collapsed when the monsoons shifted. California has 1,500 dams. Same bet, same climate."

When providing the CONTEXT field, write it as: "From [article title] on History Future Now"
"""

PLATFORM_HOOKS = {
    "x": """PLATFORM: X (Twitter)
- Sharp, fast, one thought. Imagine texting a friend a link with one sentence of why.
- The chart image does the visual work — your words provoke, the chart proves.
- Keep it punchy: 1-2 sentences for short, numbered points for long.""",
    "linkedin": """PLATFORM: LinkedIn
- First line visible before the fold — it must work alone as a reason to click "see more".
- 2-3 short paragraphs with line breaks between them.
- A question at the end only if it's genuinely interesting, not an engagement prompt.
- LinkedIn truncates after ~210 chars — first line MUST hook on its own."""
}


def _get_full_article_text(slug):
    """Read full article markdown + share_summary from essays/ directory."""
    path = HFN_CONTENT_DIR / f"{slug}.md"
    if not path.exists():
        return "", ""
    text = path.read_text(encoding="utf-8")
    # Strip frontmatter, extract share_summary
    m = re.match(r'^---\s*\n(.*?)\n---\s*\n', text, re.DOTALL)
    share_summary = ""
    body = text
    if m:
        import yaml
        try:
            fm = yaml.safe_load(m.group(1))
            share_summary = fm.get("share_summary", "")
        except Exception:
            pass
        body = text[m.end():]
    # Strip any stray code fences
    body = re.sub(r'^```\w*\s*$', '', body, flags=re.MULTILINE).strip()
    return body, share_summary

def get_client():
    if not ANTHROPIC_API_KEY: return None
    return anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

def _compute_confidence(news, article, chart, hook_strategy=""):
    """Compute confidence score (0-1) for auto-confirm decisions.
    Based on: relevance (0.5), prior article performance (0.2), strategy track record (0.3)."""
    score = 0.0
    # Relevance component (0-0.5)
    score += min(news.get("relevance_score", 0), 1.0) * 0.5
    # Article has prior performance data (0-0.2)
    if article and article.get("id"):
        perf = db.get_article_performance(article["id"])
        if perf and perf.get("total_posts", 0) > 0:
            score += 0.1
            if (perf.get("clicks_30d") or 0) > 0:
                score += 0.1
    # Hook strategy has won A/B tests (0-0.3)
    if hook_strategy and article and article.get("id"):
        wins = db.get_winning_strategies(article["id"])
        for w in wins:
            if w["winning_strategy"] == hook_strategy:
                score += 0.3
                break
        else:
            # No win data but strategy exists — moderate confidence
            if wins:
                score += 0.1
            else:
                score += 0.15  # no A/B data at all — neutral
    else:
        score += 0.15
    return round(min(score, 1.0), 2)

def build_feedback_prompt():
    """Build a prompt section from past feedback."""
    fb = db.get_feedback_summary()
    lines = []
    if fb["rejections"]:
        lines.append("USER PREFERENCES (learned from past rejections):")
        for r in fb["rejections"][:10]:
            if r["reason"]:
                lines.append(f"  - Rejected {r['post_type']} on {r['platform']}: {r['reason']}")
    if fb["edits"]:
        lines.append("\nEDIT PATTERNS (user changed these):")
        for e in fb["edits"][:5]:
            lines.append(f"  - Original: {e['original_caption'][:80]}...")
            lines.append(f"    Changed to: {e['edited_caption'][:80]}...")
    top = db.get_top_performing_posts(5)
    if top:
        lines.append("\nTOP-PERFORMING POSTS (ranked by engagement quality, not raw clicks):")
        for t in top:
            qs = t.get('quality_score', 0) or 0
            lines.append(f"  - {t['platform']} {t.get('post_type','short')}: \"{t['caption'][:80]}...\" — quality {qs} ({t['clicks_30d']} clicks)")
    conn = db.get_db()
    match_rejects = db._dicts(conn.execute(
        "SELECT reason, platform FROM feedback WHERE action='match_reject' ORDER BY created_at DESC LIMIT 5"
    ).fetchall())
    conn.close()
    if match_rejects:
        lines.append("\nREJECTED MATCHES (user removed these pairings from plan):")
        for r in match_rejects:
            lines.append(f"  - {r['reason']}")
    return "\n".join(lines) if lines else ""

def build_article_feedback_prompt(article_id):
    """Build per-article performance insights for the generation prompt."""
    if not article_id:
        return ""
    feedback = db.get_article_feedback(article_id)
    if not feedback:
        return ""
    lines = ["\nARTICLE-SPECIFIC INSIGHTS (from past posts about THIS article):"]
    # Compute quality score per post
    def _qs(f):
        clicks = f.get("clicks_30d") or 0
        if not clicks: return 0
        bounce = f.get("bounce_rate") if f.get("bounce_rate") is not None else 0.5
        dur = f.get("avg_session_duration") if f.get("avg_session_duration") is not None else 60
        return round(clicks * (1 - bounce) * min(dur / 120, 1), 1)

    # Group by hook_strategy and compute average quality
    strategy_perf = {}
    for f in feedback:
        hs = f.get("hook_strategy") or "unknown"
        if hs not in strategy_perf:
            strategy_perf[hs] = {"scores": [], "count": 0}
        strategy_perf[hs]["scores"].append(_qs(f))
        strategy_perf[hs]["count"] += 1
    if len(strategy_perf) > 1:
        lines.append("  Hook strategy performance (quality score = clicks adjusted for engagement depth):")
        for hs, data in sorted(strategy_perf.items(),
                                key=lambda x: sum(x[1]["scores"]) / max(len(x[1]["scores"]), 1),
                                reverse=True):
            avg = sum(data["scores"]) / max(len(data["scores"]), 1)
            lines.append(f"    {hs}: {avg:.1f} avg quality ({data['count']} posts)")
    # Platform comparison
    plat_perf = {}
    for f in feedback:
        plat = f.get("platform", "unknown")
        if plat not in plat_perf:
            plat_perf[plat] = []
        plat_perf[plat].append(_qs(f))
    if len(plat_perf) > 1:
        lines.append("  Platform performance:")
        for plat, scores in plat_perf.items():
            lines.append(f"    {plat}: {sum(scores)/len(scores):.1f} avg quality")
    # Top performing post example
    top = [f for f in feedback if (f.get("clicks_30d") or 0) > 0]
    if top:
        best = top[0]
        lines.append(f"  Best post: {best.get('hook_strategy','?')} on {best['platform']} — {best['clicks_30d']} clicks")
        lines.append(f"    Caption start: \"{(best.get('caption','')[:80])}...\"")
    # A/B test results
    wins = db.get_winning_strategies(article_id)
    if wins:
        lines.append("  A/B test results:")
        for w in wins[:3]:
            lines.append(f"    {w['winning_strategy']} beat {w['losing_strategy']} on {w['platform']} ({w['win_clicks']} vs {w['lose_clicks']} clicks)")
    return "\n".join(lines) if len(lines) > 1 else ""

def gen_post(news, chart, article, platform, post_type="short", force_strategy=None):
    """Generate a single post. Unified function for short and long."""
    client = get_client()
    if not client: return None
    url = article["url"] if article else f"{HFN_BASE_URL}/charts"
    feedback = build_feedback_prompt()
    article_feedback = build_article_feedback_prompt(article.get("id") if article else None)

    # Get full article text and share_summary from disk
    slug = article.get("slug", "")
    full_body, share_summary = _get_full_article_text(slug) if slug else ("", "")

    share_line = ""
    if share_summary:
        share_line = f"\nARTICLE SHARE SUMMARY (the author's own pitch — match this quality, don't copy it): {share_summary}"

    strategy_instruction = ""
    if force_strategy:
        strategy_instruction = f"\nYou MUST use the {force_strategy} approach. Do not use any other."

    if post_type == "short":
        content_instruction = f"""Write a SHORT post (the chart image will be shown alongside):
1. CAPTION ({"max 220 chars" if platform == "x" else "max 600 chars"}):
   - The chart is attached as an image. Do not describe what it shows — provoke curiosity about it.
   - Connect to the news story in one sharp sentence. The reader should think "I need to see that article."{strategy_instruction}
   {"- No hashtags." if platform == "x" else "- End with 2-3 hashtags."}
   {"" if platform == "x" else "- Use 2-3 short paragraphs with line breaks."}
2. CONTEXT ({"max 80 chars" if platform == "x" else "max 120 chars"}):
   Write as: "From [article title] on History Future Now"
3. HOOK_STRATEGY: Describe your approach in 1-2 words (e.g. "contrast", "historical parallel", "provocative claim").
Return JSON: {{"caption": "...", "context": "...", "hook_strategy": "..."}}"""
        max_tok = 400
    else:
        # Use full article text from disk (up to 12k chars), fall back to DB excerpt
        article_text = full_body[:12000] if full_body else article.get("full_text", article.get("opening", ""))[:4000]
        max_chars = "1800" if platform == "x" else "2500"
        platform_note = "Structure as numbered points for threadability." if platform == "x" else "Use paragraph breaks. First paragraph must work alone before the fold."
        content_instruction = f"""Write a {"thread-style post" if platform == "x" else "LinkedIn article"} (max {max_chars} chars):
- Read the article content below carefully. Find the most interesting, specific, surprising thing in it. Lead with that.{strategy_instruction}
- Connect to today's news headline naturally — not as a forced bridge, but because the parallel is genuinely interesting.
- Draw 2-3 historical parallels or insights from the article. Use specific numbers, dates, and comparisons from the text.
- End with a thought that makes the reader want the full picture. Do NOT include the URL — it is appended automatically.
- {platform_note}
{"- No hashtags" if platform == "x" else "- End with 2-3 relevant hashtags"}

ARTICLE CONTENT:
{article_text}

Also provide a short CONTEXT line (max 100 chars): "From [article title] on History Future Now"
Also provide HOOK_STRATEGY: describe your approach in 1-2 words (e.g. "contrast", "historical parallel", "provocative claim").
Return JSON: {{"caption": "...", "context": "...", "hook_strategy": "..."}}"""
        max_tok = 1500

    platform_hook = PLATFORM_HOOKS.get(platform, "")
    prompt = f"""{VOICE}

{platform_hook}
{share_line}

{feedback}
{article_feedback}

NEWS: {news['title']}
{news.get('summary', '')[:200]}
CHART: {chart['title']} — {chart['description']}
SOURCE: {chart['source']}
ARTICLE: {article['title']} ({article['part']})

{content_instruction}
JSON only, no markdown fences."""

    try:
        resp = client.messages.create(model=GEN_MODEL, max_tokens=max_tok,
                                      messages=[{"role": "user", "content": prompt}])
        text = resp.content[0].text.strip()
        text = text.replace('```json', '').replace('```', '').strip()
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m: return json.loads(m.group())
    except Exception as ex:
        print(f"  [!] Gen error ({platform} {post_type}): {ex}")
    return None


def generate_from_matches():
    """Generate posts from matched news. Smart dedup: 1 post per chart per platform."""
    matched = db.get_matched_news(MIN_RELEVANCE, 30)

    # Track existing posts to avoid regeneration
    existing_keys = set()
    for p in db.get_drafts() + db.get_posted() + db.get_scheduled():
        key = (p.get("chart_id"), p.get("platform"), p.get("post_type"))
        existing_keys.add(key)
        # Also track by news_item_id
        if p.get("news_item_id"):
            existing_keys.add(("news", p["news_item_id"], p["platform"]))

    # Get recently used charts to avoid repetition
    recent_charts = db.get_charts_used_recently(3)

    # Group by chart_id: pick the best news story per chart
    best_per_chart = {}
    for m in matched:
        cid = m.get("matched_chart_id")
        if not cid: continue
        if cid not in best_per_chart or m["relevance_score"] > best_per_chart[cid]["relevance_score"]:
            best_per_chart[cid] = m

    to_gen = list(best_per_chart.values())
    if not to_gen:
        print("  No new chart matches to generate from")
        return 0

    charts = {c["id"]: c for c in db.get_all_charts()}
    generated = 0

    for news in to_gen:
        chart = charts.get(news["matched_chart_id"])
        if not chart or not chart.get("image_path"):
            continue

        article = None
        if news.get("matched_article_id"):
            article = db.get_article(news["matched_article_id"])
        if not article:
            article = db.get_article_by_slug(chart["article_slug"])
        if not article:
            continue
        if article.get("status") == "deleted":
            continue

        score = news.get("relevance_score", 0)
        high_relevance = score >= 0.7
        recently_used = chart["id"] in recent_charts

        if recently_used:
            print(f"  ⏭ [{score:.1f}] Skipping (chart used recently): {chart['title'][:50]}")
            continue

        # Lifecycle-aware threshold (Feature 2)
        lifecycle = db.get_article_lifecycle(article["id"])
        stage = lifecycle["stage"]
        if stage == "launch":
            threshold = 0.5
        elif stage == "active":
            threshold = 0.6
        else:  # evergreen
            threshold = 0.7
        if score < threshold:
            print(f"  ⏭ [{score:.1f}] Below {stage} threshold ({threshold}): {chart['title'][:50]}")
            continue

        print(f"\n  {'★' if high_relevance else '·'} [{score:.1f}] [{stage}] {news['title'][:55]}...")

        platforms = ["x", "linkedin"] if is_linkedin_safe(article) else ["x"]
        for platform in platforms:
            # Decide: short or long (not both by default)
            post_type = "long" if high_relevance else "short"
            key = (chart["id"], platform, post_type)

            if key in existing_keys:
                continue
            if ("news", news["id"], platform) in existing_keys:
                continue

            # A/B testing: 30% chance on high-relevance matches (Feature 6)
            if high_relevance and random.random() < 0.3:
                variant_group = f"ab_{uuid.uuid4().hex[:8]}"
                strategies = random.sample(["QUESTION", "CONTRAST", "PROVOCATIVE_CLAIM",
                                            "HISTORICAL_PARALLEL", "NUMBER"], 2)
                ab_pids = []
                for strategy in strategies:
                    result = gen_post(news, chart, article, platform, post_type,
                                      force_strategy=strategy)
                    if result:
                        caption = result.get("essay", result.get("caption", ""))
                        context = result.get("context", "")
                        hook_strategy = result.get("hook_strategy", strategy)
                        conf = _compute_confidence(news, article, chart, hook_strategy)
                        pid = db.insert_post(
                            news_item_id=news["id"], chart_id=chart["id"],
                            article_id=article["id"], platform=platform,
                            caption=caption, article_context=context,
                            article_url=article["url"],
                            image_path=chart["image_path"],
                            post_type=post_type, hook_strategy=hook_strategy,
                            variant_group=variant_group, confidence_score=conf)
                        ab_pids.append(pid)
                        generated += 1
                        print(f"    ✓ {platform} {post_type} A/B [{strategy}] (conf={conf:.2f})")
                if len(ab_pids) == 2:
                    continue  # Both variants succeeded — skip normal generation
                elif len(ab_pids) == 1:
                    # One variant failed — clear variant_group on the orphan so it's a normal post
                    conn = db.get_db()
                    conn.execute("UPDATE posts SET variant_group='' WHERE id=?", (ab_pids[0],))
                    conn.commit()
                    conn.close()
                    print(f"    ⚠ A/B partial — converted to normal post")
                    continue  # Already have one post, don't generate another

            result = gen_post(news, chart, article, platform, post_type)
            if result:
                caption = result.get("essay", result.get("caption", ""))
                context = result.get("context", "")
                hook_strategy = result.get("hook_strategy", "")
                conf = _compute_confidence(news, article, chart, hook_strategy)
                db.insert_post(
                    news_item_id=news["id"], chart_id=chart["id"],
                    article_id=article["id"], platform=platform,
                    caption=caption, article_context=context,
                    article_url=article["url"],
                    image_path=chart["image_path"],
                    post_type=post_type, hook_strategy=hook_strategy,
                    confidence_score=conf)
                generated += 1
                print(f"    ✓ {platform} {post_type} (conf={conf:.2f})")

    print(f"\n  ✓ {generated} posts generated")
    return generated

def gen_from_chart(chart_id, platform="x", post_type="short"):
    """Reverse flow: given a chart, find best recent news hook and generate a post."""
    client = get_client()
    if not client: return None

    chart = db.get_chart(chart_id)
    if not chart: return None
    article = db.get_article_by_slug(chart["article_slug"])
    if not article: return None

    recent = db.get_recent_news_for_matching(30)
    if not recent: return None

    news_list = "\n".join(f"NEWS_{n['id']}: {n['title']}" for n in recent[:20])

    match_prompt = f"""Pick the single best news story to pair with this chart.

CHART: {chart['title']} — {chart['description']}
SOURCE: {chart['source']}
ARTICLE: {article['title']} ({article['part']})

RECENT NEWS:
{news_list}

Return JSON: {{"news_id": <id>, "hook": "<one sentence connecting news to chart>"}}
If no good match, return {{"news_id": null, "hook": "<evergreen hook for this chart>"}}
JSON only, no markdown."""

    from config import MATCH_MODEL
    try:
        resp = client.messages.create(model=MATCH_MODEL, max_tokens=300,
                                      messages=[{"role": "user", "content": match_prompt}])
        text = resp.content[0].text.strip().replace('```json','').replace('```','').strip()
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m: return None
        match = json.loads(m.group())
    except Exception as ex:
        print(f"  [!] Match error: {ex}")
        return None

    news_id = match.get("news_id")
    news = next((n for n in recent if n["id"] == news_id), None) if news_id else None
    if not news:
        news = {"id": None, "title": match.get("hook", ""), "summary": ""}

    result = gen_post(news, chart, article, platform, post_type)
    if not result: return None

    caption = result.get("essay", result.get("caption", ""))
    context = result.get("context", "")
    hook_strategy = result.get("hook_strategy", "")
    pid = db.insert_post(
        news_item_id=news.get("id"), chart_id=chart["id"],
        article_id=article["id"], platform=platform,
        caption=caption, article_context=context,
        article_url=article["url"], image_path=chart["image_path"],
        post_type=post_type, hook_strategy=hook_strategy)
    return {"post_id": pid, "caption": caption, "news_title": news.get("title", "")}


def generate_planned():
    """Generate actual post text for all 'planned' posts. Called after user confirms plan."""
    planned = db.get_planned_posts()
    if not planned:
        print("  No planned posts to generate")
        return 0

    charts = {c["id"]: c for c in db.get_all_charts()}
    generated = 0

    for p in planned:
        ok = _generate_one_post(p, charts)
        if ok: generated += 1

    print(f"\n  ✓ {generated}/{len(planned)} posts generated")
    return generated


def generate_single(post_id):
    """Generate text for a single planned post."""
    conn = db.get_db()
    row = db._dict(conn.execute("""
        SELECT p.*, c.title as chart_title, c.description as chart_desc, c.image_path as chart_image,
               a.title as article_title, a.url as article_url_joined,
               n.title as news_title, n.hook
        FROM posts p
        LEFT JOIN charts c ON p.chart_id = c.id
        LEFT JOIN articles a ON p.article_id = a.id
        LEFT JOIN news_items n ON p.news_item_id = n.id
        WHERE p.id = ?
    """, (post_id,)).fetchone())
    conn.close()
    if not row:
        return False
    charts = {c["id"]: c for c in db.get_all_charts()}
    return _generate_one_post(row, charts)


def _generate_one_post(p, charts):
    """Internal: generate text for one post record. Returns True on success."""
    chart = charts.get(p.get("chart_id"))
    article = None

    # Try to find article - multiple fallbacks
    if p.get("article_id"):
        article = db.get_article(p["article_id"])
    if not article and chart and chart.get("article_slug"):
        article = db.get_article_by_slug(chart["article_slug"])
    if not article and p.get("news_item_id"):
        # Look up from the news item's matched article
        conn = db.get_db()
        news_row = conn.execute(
            "SELECT matched_article_id FROM news_items WHERE id=?",
            (p["news_item_id"],)).fetchone()
        conn.close()
        if news_row and news_row[0]:
            article = db.get_article(news_row[0])

    if not article:
        print(f"  ✗ Post #{p['id']}: no article found (article_id={p.get('article_id')}, chart_id={p.get('chart_id')})")
        return False

    # For text-only posts (no chart), find first chart with image from this article
    if not chart:
        slug = article.get("slug","")
        if slug:
            conn = db.get_db()
            row = conn.execute(
                "SELECT * FROM charts WHERE article_slug=? AND image_path != '' ORDER BY figure_num LIMIT 1",
                (slug,)).fetchone()
            conn.close()
            if row:
                chart = dict(row)
            else:
                chart = {"id": 0, "title": article.get("title",""),
                         "description": article.get("excerpt",""),
                         "image_path": "", "article_slug": slug, "source": ""}
        else:
            chart = {"id": 0, "title": article.get("title",""),
                     "description": article.get("excerpt",""),
                     "image_path": "", "article_slug": "", "source": ""}
    elif not chart.get("image_path"):
        # Chart exists but has no image - try to find one from same article
        slug = chart.get("article_slug","")
        if slug:
            conn = db.get_db()
            img_row = conn.execute(
                "SELECT image_path FROM charts WHERE article_slug=? AND image_path != '' LIMIT 1",
                (slug,)).fetchone()
            conn.close()
            if img_row:
                chart["image_path"] = img_row[0]

    news = {"id": p.get("news_item_id"), "title": p.get("news_title", ""),
            "summary": p.get("hook", "")}

    print(f"  Generating {p['platform']} {p.get('post_type','short')} for: {chart['title'][:50]}...")

    result = gen_post(news, chart, article, p["platform"], p.get("post_type", "short"))
    if result:
        caption = result.get("essay", result.get("caption", ""))
        context = result.get("context", "")
        hook_strategy = result.get("hook_strategy", "")
        conn = db.get_db()
        conn.execute("""UPDATE posts SET caption=?, article_context=?, article_url=?,
                       image_path=?, hook_strategy=?, status='generated' WHERE id=?""",
                     (caption, context, article.get("url",""),
                      chart.get("image_path",""), hook_strategy, p["id"]))
        conn.commit()
        conn.close()
        print(f"    ✓ Done")
        return True
    else:
        print(f"    ✗ Failed")
        return False


def gen_carousel_slides(article, charts):
    """Distil an article into carousel slide content using Claude Opus.

    Args:
        article: dict with title, slug, part, url, excerpt
        charts: list of chart dicts with id, title, description, source, image_path

    Returns: list of slide dicts or None on failure
    """
    client = get_client()
    if not client:
        return None

    slug = article.get("slug", "")
    full_body, share_summary = _get_full_article_text(slug) if slug else ("", "")
    if not full_body:
        print(f"  [!] No article text found for {slug}")
        return None

    charts_with_images = [c for c in charts if c.get("image_path")]
    charts_desc = "\n".join(
        f"CHART_{c['id']}: Fig {c.get('figure_num', '?')} — {c['title']} | {(c.get('description') or '')[:150]} | Source: {c.get('source', 'N/A')}"
        for c in charts_with_images
    )

    prompt = f"""{VOICE}

You are creating content for a LinkedIn carousel (swipeable PDF slides) about this article.
The carousel will have a branded title slide and CTA slide automatically — you only need to provide the CONTENT slides.

ARTICLE: {article['title']} ({article.get('part', '')})
{full_body[:10000].rsplit('. ', 1)[0] + '.' if len(full_body) > 10000 else full_body}

AVAILABLE CHARTS (with images):
{charts_desc if charts_desc else '(no charts with images)'}

INSTRUCTIONS:
1. Extract 4-6 key insights from the article. Each MUST include a specific number, date, or historical fact.
2. Select 1-3 charts that best support your insights (by chart ID). Only pick charts that have images.
3. Write headings (max 8 words each) and body text (max 40 words per slide).
4. Include at least one historical parallel or surprising comparison.
5. Match HFN voice: British English, confident, specific, no AI filler.
6. Order slides for narrative flow — each should build on the previous.
7. Total content slides: 5-8 (mix of insights and charts).

Return JSON array. Two types:
- Insight: {{"type": "insight", "heading": "Short punchy heading", "body": "1-2 sentence insight with a specific number or date."}}
- Chart: {{"type": "chart", "chart_id": <id>, "context": "One sentence explaining the 'so what' of this chart."}}

JSON array only, no markdown fences."""

    try:
        resp = client.messages.create(
            model=GEN_MODEL, max_tokens=2000,
            messages=[{"role": "user", "content": prompt}]
        )
        text = resp.content[0].text.strip()
        text = text.replace('```json', '').replace('```', '').strip()
        m = re.search(r"\[.*\]", text, re.DOTALL)
        if m:
            slides = json.loads(m.group())
            print(f"  ✓ Generated {len(slides)} carousel slides")
            return slides
    except Exception as ex:
        print(f"  [!] Carousel gen error: {ex}")
    return None


def gen_carousel_caption(article, slide_count):
    """Generate a LinkedIn caption specifically for a carousel post.

    Unlike gen_post(), this knows the post has a swipeable document attached
    and should invite engagement without including a URL (the CTA slide has it).
    """
    client = get_client()
    if not client:
        return None

    slug = article.get("slug", "")
    _, share_summary = _get_full_article_text(slug) if slug else ("", "")
    share_line = f"\nARTICLE SHARE SUMMARY: {share_summary}" if share_summary else ""

    prompt = f"""{VOICE}

Write a LinkedIn caption for a CAROUSEL POST (swipeable PDF document) about this article.

ARTICLE: {article['title']} ({article.get('part', '')})
{article.get('excerpt', '')[:500]}
{share_line}

The carousel has {slide_count} slides with key insights and charts from the article.

RULES:
1. The carousel is the content — your caption introduces it and invites swiping.
2. DO NOT include any URL. The article link is on the final slide.
3. Open with one provocative sentence that makes someone stop scrolling.
4. Reference what's IN the carousel: "Swipe through..." or "X slides on..." or "The data tells a story..."
5. Keep it under 700 characters. 2-3 short paragraphs.
6. End with 2-3 hashtags.
7. British English. Confident, specific, no AI filler.

Return JSON: {{"caption": "...", "hook_strategy": "..."}}
JSON only, no markdown fences."""

    try:
        resp = client.messages.create(
            model=GEN_MODEL, max_tokens=400,
            messages=[{"role": "user", "content": prompt}]
        )
        text = resp.content[0].text.strip()
        text = text.replace('```json', '').replace('```', '').strip()
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if m:
            return json.loads(m.group())
    except Exception as ex:
        print(f"  [!] Carousel caption gen error: {ex}")
    return None


if __name__ == "__main__":
    generate_from_matches()
